GWL_EXSTYLE = -20
WS_EX_APPWINDOW = 0x00040000
WS_EX_TOOLWINDOW = 0x00000080

CAPTURE_WIDTH = 720
CAPTURE_HEIGHT = 405

"""Colors"""
COLOR_BLACK = "#232932"
COLOR_GRAY = "#393E46"
COLOR_BLUE = "#01ADB5"
COLOR_WHITE = "#EEEEEE"

"""Paths"""
PATH_IMAGES = "src/images/"
PATH_ICONS = "src/icons/"

"""Hand Landmarks"""
WRIST = 0
THUMB_CMC = 1
THUMB_MCP = 2
THUMB_IP = 3
THUMB_TIP = 4
INDEX_FINGER_MCP = 5
INDEX_FINGER_PIP = 6
INDEX_FINGER_DIP = 7
INDEX_FINGER_TIP = 8
MIDDLE_FINGER_MCP = 9
MIDDLE_FINGER_PIP = 10
MIDDLE_FINGER_DIP = 11
MIDDLE_FINGER_TIP = 12
RING_FINGER_MCP = 13
RING_FINGER_PIP = 14
RING_FINGER_DIP = 15
RING_FINGER_TIP = 16
PINKY_MCP = 17
PINKY_PIP = 18
PINKY_DIP = 19
PINKY_TIP = 20

""" Gestures """
GESTURE_DRAG = "drag"
GESTURE_DELETE = "delete"
